### PR TITLE
Merge 'main' branch into 'multiview-prototype'

### PR DESCRIPTION
**Pull request by loic-sharma**
This merges `main` into `multiview-prototype` and handles merge conflicts.

Please review that my `PlatformDispatcher` merge seems reasonable. GitHub's UI struggles to load the diff, so here is [the diff](https://www.diffchecker.com/OvEF8YLL) of the current `multiview-prototype`'s `PlatformDispatcher` versus this PR's `PlatformDispatcher`.

### Test

Test build & unit tests & multi-view samples
* [x] Windows
* [x] macOS. ⚠️ Notes:
    * The MVP playground apps get errors caused by the `flutter/lifecycle` platform channel
    * The `flutter_desktop_darwin_unittests` target has test failures. They seem to be unrelated to this merge though.
* [x] Linux

/cc @dkwingsmt @goderbauer

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
RSLGTM

The `PlatformDispatcher` diff looks reasonable.

**Comment by goderbauer** [comment]
cc @CoderDake once this merges, your trouble with the `multiview-prototype` engine branch should be resolved.

**Comment by dkwingsmt** [comment]
The PlatformDispatcher diff looks reasonable :)

**Comment by goderbauer** [comment]
> The MVP playground apps get errors caused by the flutter/lifecycle platform channel

This is new with this merge? What are the errors?

**Comment by loic-sharma** [comment]
> > The MVP playground apps get errors caused by the flutter/lifecycle platform channel
> 
> This is new with this merge? What are the errors?

The playground apps work as expected but the console log errors happen whenever I focus/onfocus a window. I believe it is new with the merge, I didn't see these errors before.

Errors:

```
flutter: A message on the flutter/lifecycle channel was discarded before it could be handled.
This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register a listener. See the ChannelBuffers API documentation for details on how to configure the channel to expect more messages, or to expect messages to get discarded:
  https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html
The capacity of the flutter/lifecycle channel is 1 message.
```

**Comment by dkwingsmt** [comment]
This error means that the messages of this channel are not handled and are discarded when new ones arrive. Did you get these errors on the apps that use the bare dart:ui APIs (which should be expected), or that use the full Flutter framework?

**Comment by loic-sharma** [comment]
@dkwingsmt and I talked offline. I'll merge now to unblock others and will follow-up with an investigation for the lifecycle errors

**Pull request merged**
